name = "Minecraft Extended 2"
author = "Wizard Dragon"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "22dca8cb6c31decc9836da1cd525756fdc034b1a7b33562bc7a502d253076b5b"

[versions]
minecraft = "1.20.1"
quilt = "0.25.0"

[options]
datapack-folder = "config/paxi/datapacks"
